### PR TITLE
1.0.6 add Help (to list all shortcuts); 50% ready for Travis CI build

### PR DESCRIPTION
**Pull request by paulvi**
1.0.6 add Help (to list all shortcuts); 50% ready for Travis CI build

### CODE REVIEW

**Comment by paulvi** [comment]
to make it 100% ready for Travis mavenize, i.e. just add pom.xml (e.g. https://github.com/Nodeclipse/nodeclipse-1/blob/master/pom.xml ) or ant (can't help with that)

Though Eclipse Export works great and enough for now.

**Comment by paulvi** [comment]
screenshot 
handysplit

**Comment by akikhtenko** [comment]
Thank you for the pull request. Will get the changes rolled out onto the update site tonight.

**Comment by paulvi** [comment]
welcome

**Pull request merged**
